bot:
    token: "<bot token>"
    client_id: "<client id>"
    prefix: "."

ids:
    creators: 
      - 188735535169273858
      - 232971316880343051
    benny: 234048816033038337

originator: 
    name: "<name (nick or some identifying name)>"

database:
    url: "..."
    user: "..."
    password: "..."
    database: "..."
    host: "..."
    port: 0000

emoji:
    _0: "\u0030\u20e3"
    _1: "\u0031\u20e3"
    _2: "\u0032\u20e3"
    _3: "\u0033\u20e3"
    _4: "\u0034\u20e3"
    _5: "\u0035\u20e3"
    _6: "\u0036\u20e3"
    _7: "\u0037\u20e3"
    _8: "\u0038\u20e3"
    _9: "\u0039\u20e3"
    checkmark: "\u2705"
